---
name: CICD
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

env:
  GOVER: 1.16.4
  CGO_ENABLED: 0

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - run: go test -cover ./...

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up go lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0

  build-and-release:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - unit-test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # version: v0.155.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_TOKEN: ${{ secrets.FURYPUSHTOKEN }}
